on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: kubesphere/kubekey
          upstream_branch: master
          target_branch: master
          git_pull_args: --ff-only
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."

      - name: Timestamp
        run: date
